### ISSUE TITLE
Sprite component link up

### ISSUE THREAD

**Issue by bkawk** [bkawk/SwarmCity-EOS#1]
The Sprite component is being passed values in the header as seen here:

https://github.com/bkawk/SwarmCity-EOS/blob/master/src/components/component-header.js#L65-L73

Those values have been added as properties to the component here 

https://github.com/bkawk/SwarmCity-EOS/blob/master/src/components/component-sprite.js#L29-L66

But they now need linking to the CSS so we can reuse this component again. We also need to detect the screen density and use the @2x or the @1x sprite images.

After further discussion:

Sprite resolution will work in 2 phases: 

- Sprite component will decide on the @2x or the @1x sprite images depending on the @media query checking if the screen is retina or not.
- The sprite component will include a shared-sprites file. The Sprite component will get passed an icon name value which will resolve in the shared-sprites file to the correct sprite coordinates of that icon.

**Comment by bkawk** [comment]
Great update, I feel we found the best solution!

**Comment by xardass** [comment]
I sent a PR where all the sprite logic is within the sprite component. Every icon will need its own class within that component, until we add the shared-sprites file. I will have to figure out how to add the right mixin depending on icon-name value then.

**Comment by bkawk** [comment]
Its nice simple solution, I just merged the PR with thanks
